dataset: './params/custom_wsis.csv'
feature_extractors: './params/feature_extractors.csv'
wsi_dir: '/mnt/beegfs/labs/DiGenomaLab/Machine_Learning/cancer_histology/data/tcga_gdc/images/tcga_brca/'
outdir: "results"
trident_dir: /mnt/beegfs/home/g.cabas/TRIDENT/